services:
  inverter_manyi:
    build: .
    container_name: inverter_manyi
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "app.py"]
    privileged: true
    pid: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tesla_http_proxy


  grafana:
      image: grafana/grafana-oss:latest
      container_name: grafana
      restart: unless-stopped
      ports:
        - "13000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=mercatello
        - GF_INSTALL_PLUGINS=frser-sqlite-datasource
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      volumes:
        - grafana_data:/var/lib/grafana
        - ./data:/data
      extra_hosts:
        - "host.docker.internal:host-gateway"  
      depends_on:
        - inverter_manyi
  
  # battery_fit:
  #   build: .
  #   container_name: battery_fit
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #     - ./tools/statistics:/app/tools/statistics
  #   restart: "no"
  #   command: ["tail", "-f", "/dev/null"]


  tesla_http_proxy:
    image: tesla/vehicle-command:latest
    container_name: tesla_http_proxy
    ports:
      - "4443:4443"
    environment:
      - TESLA_HTTP_PROXY_TLS_CERT=/config/cert.pem
      - TESLA_HTTP_PROXY_TLS_KEY=/config/key.pem
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=4443
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/config/private-key.pem
      - TESLA_VERBOSE=true
    volumes:
      - ./tesla-proxy-config:/config
      - ./tesla-proxy-home:/home/nonroot
    restart: unless-stopped


volumes:
  grafana_data: