services:
  inverter_manyi:
    build: .
    container_name: inverter_manyi
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - /home/sergio/Scrivania/docker/gestione_impianto/lan_scanner/src/data:/app/lan_scanner_data
    restart: unless-stopped
    command: ["python", "energy_manager_server.py"]
    #command: ["tail", "-f", "/dev/null"]
    privileged: true
    pid: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - tesla_http_proxy
      - solar_mariadb

  
  # Quando ti serve: docker compose --profile devtools up -d
  # Quando hai finito: docker rm -f inverter_manyi_dev
  
  inverter_manyi_dev:
    build: .
    container_name: inverter_manyi_dev
    env_file:
      - .env
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - /home/sergio/Scrivania/docker/gestione_impianto/lan_scanner/src/data:/app/lan_scanner_data
    command: ["tail", "-f", "/dev/null"]
    profiles:
      - devtools
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    pid: host  
    depends_on:
      - tesla_http_proxy

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=mercatello
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - inverter_manyi

  tesla_http_proxy:
    image: tesla/vehicle-command:latest
    container_name: tesla_http_proxy
    ports:
      - "4443:4443"
    environment:
      - TESLA_HTTP_PROXY_TLS_CERT=/config/cert.pem
      - TESLA_HTTP_PROXY_TLS_KEY=/config/key.pem
      - TESLA_HTTP_PROXY_HOST=0.0.0.0
      - TESLA_HTTP_PROXY_PORT=4443
      - TESLA_HTTP_PROXY_TIMEOUT=10s
      - TESLA_KEY_FILE=/config/private-key.pem
      - TESLA_VERBOSE=true
    volumes:
      - ./tesla-proxy-config:/config
      - ./tesla-proxy-home:/home/nonroot
    restart: unless-stopped

  solar_mariadb:
    image: mariadb:11
    container_name: solar_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_DATABASE=solar_db
    ports:
      - "13307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql



  tesla_charge_controller:
    build: .
    container_name: tesla_charge_controller
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    #command: ["python", "tesla_charge_controller.py"]
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - solar_mariadb
      - tesla_http_proxy
      - inverter_manyi    
volumes:
  grafana_data:
  mariadb_data: