"""baseline for MariaDB

Revision ID: 26aa452744b4
Revises: 
Create Date: 2026-05-21 13:59:19.085947
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '26aa452744b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('login_payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auth_tokens_created_at', 'auth_tokens', ['created_at'], unique=False)
    op.create_table('device_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_row_key', sa.String(length=255), nullable=False),
    sa.Column('update_time', sa.Text(), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_snapshots_created_at', 'device_snapshots', ['created_at'], unique=False)
    op.create_index('idx_device_snapshots_device_row_key', 'device_snapshots', ['device_row_key'], unique=False)
    op.create_table('device_snapshots_flat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_row_key', sa.String(length=255), nullable=False),
    sa.Column('update_time', sa.Text(), nullable=True),
    sa.Column('inverter_program_version', sa.Text(), nullable=True),
    sa.Column('internal_model', sa.Text(), nullable=True),
    sa.Column('input_voltage', sa.Text(), nullable=True),
    sa.Column('input_frequency', sa.Text(), nullable=True),
    sa.Column('output_voltage', sa.Text(), nullable=True),
    sa.Column('output_frequency', sa.Text(), nullable=True),
    sa.Column('battery_voltage', sa.Text(), nullable=True),
    sa.Column('battery_capacity', sa.Text(), nullable=True),
    sa.Column('inverter_charging_current', sa.Text(), nullable=True),
    sa.Column('load_percentage', sa.Text(), nullable=True),
    sa.Column('device_temp', sa.Text(), nullable=True),
    sa.Column('machine_status_code', sa.Text(), nullable=True),
    sa.Column('system_run_time', sa.Text(), nullable=True),
    sa.Column('system_operation_status', sa.Text(), nullable=True),
    sa.Column('battery_number_in_series', sa.Text(), nullable=True),
    sa.Column('controller_program_version', sa.Text(), nullable=True),
    sa.Column('pv_voltage', sa.Text(), nullable=True),
    sa.Column('controller_charging_current', sa.Text(), nullable=True),
    sa.Column('controller_temp', sa.Text(), nullable=True),
    sa.Column('controller_status_code', sa.Text(), nullable=True),
    sa.Column('controller_connection_status', sa.Text(), nullable=True),
    sa.Column('controller_charging_status', sa.Text(), nullable=True),
    sa.Column('inverter_charge_status', sa.Text(), nullable=True),
    sa.Column('battery_voltage_is_full', sa.Text(), nullable=True),
    sa.Column('controller_malfunction_alarm', sa.Text(), nullable=True),
    sa.Column('controller_warning_alarm', sa.Text(), nullable=True),
    sa.Column('inverter_fault_alarm', sa.Text(), nullable=True),
    sa.Column('inverter_warning_alarm', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_snapshots_flat_created_at', 'device_snapshots_flat', ['created_at'], unique=False)
    op.create_index('idx_device_snapshots_flat_device_row_key', 'device_snapshots_flat', ['device_row_key'], unique=False)
    op.create_table('host_status_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=True),
    sa.Column('ip_status', sa.Text(), nullable=True),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('macaddress', sa.Text(), nullable=True),
    sa.Column('service', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relay_status_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('relay_id', sa.Text(), nullable=True),
    sa.Column('is_on', sa.Integer(), nullable=True),
    sa.Column('real_state', sa.Integer(), nullable=True),
    sa.Column('feedback_invert', sa.Integer(), nullable=True),
    sa.Column('feedback_pin', sa.Integer(), nullable=True),
    sa.Column('relay_pin', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_measurement_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('measurement_config_id', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('apparent_power', sa.Float(), nullable=True),
    sa.Column('relay_real_state', sa.Integer(), nullable=True),
    sa.Column('total_power', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_measurements_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.Column('http_method', sa.String(length=255), server_default='GET', nullable=True),
    sa.Column('endpoint_query', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('response_structure', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=True),
    sa.Column('port', sa.Integer(), server_default='80', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('sensor_name', sa.Text(), nullable=False),
    sa.Column('sensor_type', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('macaddress', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('channel_index', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('power_factor', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('total_power', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_status_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Integer(), nullable=True),
    sa.Column('ip_status', sa.Text(), nullable=True),
    sa.Column('wifi_ssid', sa.Text(), nullable=True),
    sa.Column('wifi_rssi', sa.Integer(), nullable=True),
    sa.Column('uptime_s', sa.Integer(), nullable=True),
    sa.Column('heap_free', sa.Integer(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tesla_vehicle_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('vin', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('charging_state', sa.Text(), nullable=True),
    sa.Column('charge_limit_soc', sa.Float(), nullable=True),
    sa.Column('charger_power', sa.Float(), nullable=True),
    sa.Column('inside_temp', sa.Float(), nullable=True),
    sa.Column('outside_temp', sa.Float(), nullable=True),
    sa.Column('locked', sa.Integer(), nullable=True),
    sa.Column('charge_port_door_open', sa.Integer(), nullable=True),
    sa.Column('charge_port_latch', sa.Text(), nullable=True),
    sa.Column('charge_port_color', sa.Text(), nullable=True),
    sa.Column('conn_charge_cable', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tesla_vehicle_snapshots_vin_created_at', 'tesla_vehicle_snapshots', ['vin', 'created_at'], unique=False)
    op.create_table('user_info_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=255), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_info_snapshots_created_at', 'user_info_snapshots', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_info_snapshots_created_at', table_name='user_info_snapshots')
    op.drop_table('user_info_snapshots')
    op.drop_index('idx_tesla_vehicle_snapshots_vin_created_at', table_name='tesla_vehicle_snapshots')
    op.drop_table('tesla_vehicle_snapshots')
    op.drop_table('sensor_status_snapshots')
    op.drop_table('sensor_snapshots')
    op.drop_table('sensor_measurements_config')
    op.drop_table('sensor_measurement_snapshots')
    op.drop_table('relay_status_snapshots')
    op.drop_table('host_status_snapshots')
    op.drop_index('idx_device_snapshots_flat_device_row_key', table_name='device_snapshots_flat')
    op.drop_index('idx_device_snapshots_flat_created_at', table_name='device_snapshots_flat')
    op.drop_table('device_snapshots_flat')
    op.drop_index('idx_device_snapshots_device_row_key', table_name='device_snapshots')
    op.drop_index('idx_device_snapshots_created_at', table_name='device_snapshots')
    op.drop_table('device_snapshots')
    op.drop_index('idx_auth_tokens_created_at', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###