"""remove response_structure from sensor_measurements_config

Revision ID: 95ce4d913a73
Revises: 26aa452744b4
Create Date: 2026-05-21 14:27:27.329282
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '95ce4d913a73'
down_revision = '26aa452744b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_measurements_config', 'response_structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_measurements_config', sa.Column('response_structure', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###