"""add power_validated to sensor_measurement_snapshots

Revision ID: 9cac514424ef
Revises: 95ce4d913a73
Create Date: 2026-05-21 14:31:23.293762
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9cac514424ef'
down_revision = '95ce4d913a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_measurement_snapshots', sa.Column('power_validated', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_measurement_snapshots', 'power_validated')
    # ### end Alembic commands ###