"""add power_validated_zero_if_relay_on to sensor_measurements_config

Revision ID: 9d9a33b96010
Revises: 9cac514424ef
Create Date: 2026-05-21 14:40:22.152908
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9d9a33b96010'
down_revision = '9cac514424ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_measurements_config', sa.Column('power_validated_zero_if_relay_on', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_measurements_config', 'power_validated_zero_if_relay_on')
    # ### end Alembic commands ###